// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("AiMessages")]
	public class AiMessage
	{
		[Column("Id"            , IsPrimaryKey = true , IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int       Id             { get; set; } // integer
		[Column("Role"          , CanBeNull    = false                                                             )] public string    Role           { get; set; } = null!; // text
		[Column("Content"       , CanBeNull    = false                                                             )] public string    Content        { get; set; } = null!; // text
		[Column("ConversationId"                                                                                   )] public int       ConversationId { get; set; } // integer
		[Column("DateAdded"                                                                                        )] public DateTime? DateAdded      { get; set; } // timestamp (6) without time zone

		#region Associations
		/// <summary>
		/// FK_AiMessages_AiConversations_ConversationId
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(ConversationId), OtherKey = nameof(AiConversation.Id))]
		public AiConversation Conversation { get; set; } = null!;
		#endregion
	}
}
