// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("AntiAltSetting")]
	public class AntiAltSetting
	{
		[Column("Id"                   , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int      Id                    { get; set; } // integer
		[Column("MinAge"                                                                                                 )] public string?  MinAge                { get; set; } // text
		[Column("Action"                                                                                                 )] public int      Action                { get; set; } // integer
		[Column("ActionDurationMinutes"                                                                                  )] public int      ActionDurationMinutes { get; set; } // integer
		[Column("RoleId"                                                                                                 )] public ulong? RoleId                { get; set; } // numeric(20,0)
		[Column("GuildId"                                                                                                )] public ulong? GuildId               { get; set; } // numeric(20,0)
	}
}
