// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("AntiPatternPattern")]
	public class AntiPatternPattern
	{
		[Column("Id"                    , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int       Id                     { get; set; } // integer
		[Column("Pattern"                                                                                                 )] public string    Pattern                { get; set; } = null!; // text
		[Column("Name"                                                                                                    )] public string?   Name                   { get; set; } // text
		[Column("CheckUsername"                                                                                           )] public bool      CheckUsername          { get; set; } // boolean
		[Column("CheckDisplayName"                                                                                        )] public bool      CheckDisplayName       { get; set; } // boolean
		[Column("AntiPatternSettingId"                                                                                    )] public int?      AntiPatternSettingId   { get; set; } // integer
		[Column("DateAdded"                                                                                               )] public DateTime? DateAdded              { get; set; } // timestamp (6) without time zone

		#region Associations
		/// <summary>
		/// FK_AntiPatternPattern_AntiPatternSetting_AntiPatternSettingId
		/// </summary>
		[Association(ThisKey = nameof(AntiPatternSettingId), OtherKey = nameof(DataModel.AntiPatternSetting.Id))]
		public AntiPatternSetting? AntiPatternSetting { get; set; }
		#endregion
	}
}