// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("AntiSpamSetting")]
	public class AntiSpamSetting
	{
		[Column("Id"              , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int       Id               { get; set; } // integer
		[Column("Action"                                                                                            )] public int       Action           { get; set; } // integer
		[Column("MessageThreshold"                                                                                  )] public int       MessageThreshold { get; set; } // integer
		[Column("MuteTime"                                                                                          )] public int       MuteTime         { get; set; } // integer
		[Column("RoleId"                                                                                            )] public ulong?  RoleId           { get; set; } // numeric(20,0)
		[Column("DateAdded"                                                                                         )] public DateTime? DateAdded        { get; set; } // timestamp (6) without time zone
		[Column("GuildId"                                                                                           )] public ulong?  GuildId          { get; set; } // numeric(20,0)

		#region Associations
		/// <summary>
		/// FK_AntiSpamIgnore_AntiSpamSetting_AntiSpamSettingId backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(AntiSpamIgnore.AntiSpamSettingId))]
		public IEnumerable<AntiSpamIgnore> AntiSpamIgnores { get; set; } = null!;
		#endregion
	}
}
