// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("AntiPatternSetting")]
	public class AntiPatternSetting
	{
		[Column("Id"            , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int       Id             { get; set; } // integer
		[Column("Action"                                                                                          )] public int       Action         { get; set; } // integer
		[Column("PunishDuration"                                                                                  )] public int       PunishDuration { get; set; } // integer
		[Column("RoleId"                                                                                          )] public ulong?  RoleId         { get; set; } // numeric(20,0)
		[Column("DateAdded"                                                                                       )] public DateTime? DateAdded      { get; set; } // timestamp (6) without time zone
		[Column("GuildId"                                                                                         )] public ulong?  GuildId        { get; set; } // numeric(20,0)
		[Column("CheckAccountAge"                                                                                 )] public bool      CheckAccountAge     { get; set; } // boolean
		[Column("MaxAccountAgeMonths"                                                                             )] public int       MaxAccountAgeMonths { get; set; } // integer
		[Column("CheckJoinTiming"                                                                                 )] public bool      CheckJoinTiming     { get; set; } // boolean
		[Column("MaxJoinHours"                                                                                    )] public double    MaxJoinHours        { get; set; } // double precision
		[Column("CheckBatchCreation"                                                                              )] public bool      CheckBatchCreation  { get; set; } // boolean
		[Column("CheckOfflineStatus"                                                                              )] public bool      CheckOfflineStatus  { get; set; } // boolean
		[Column("CheckNewAccounts"                                                                                )] public bool      CheckNewAccounts    { get; set; } // boolean
		[Column("NewAccountDays"                                                                                  )] public int       NewAccountDays      { get; set; } // integer
		[Column("MinimumScore"                                                                                    )] public int       MinimumScore        { get; set; } // integer

		#region Associations
		/// <summary>
		/// FK_AntiPatternPattern_AntiPatternSetting_AntiPatternSettingId backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(AntiPatternPattern.AntiPatternSettingId))]
		public IEnumerable<AntiPatternPattern> AntiPatternPatterns { get; set; } = null!;
		#endregion
	}
}