// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("AntiSpamIgnore")]
	public class AntiSpamIgnore
	{
		[Column("Id"                      , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int       Id                       { get; set; } // integer
		[Column("ChannelId"                                                                                                 )] public ulong   ChannelId                { get; set; } // numeric(20,0)
		[Column("AntiSpamSettingId"                                                                                         )] public int?      AntiSpamSettingId        { get; set; } // integer
		[Column("DateAdded"                                                                                                 )] public DateTime? DateAdded                { get; set; } // timestamp (6) without time zone
		[Column("AntiMassMentionSettingId"                                                                                  )] public int?      AntiMassMentionSettingId { get; set; } // integer

		#region Associations
		/// <summary>
		/// FK_AntiSpamIgnore_AntiMassMentionSetting_AntiMassMentionSettin~
		/// </summary>
		[Association(ThisKey = nameof(AntiMassMentionSettingId), OtherKey = nameof(DataModel.AntiMassMentionSetting.Id))]
		public AntiMassMentionSetting? AntiMassMentionSetting { get; set; }

		/// <summary>
		/// FK_AntiSpamIgnore_AntiSpamSetting_AntiSpamSettingId
		/// </summary>
		[Association(ThisKey = nameof(AntiSpamSettingId), OtherKey = nameof(DataModel.AntiSpamSetting.Id))]
		public AntiSpamSetting? AntiSpamSetting { get; set; }
		#endregion
	}
}
