// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("BirthdayConfigs")]
	public class BirthdayConfig
	{
		[Column("Id"                , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int       Id                  { get; set; } // integer
		[Column("GuildId"                                                                                             )] public ulong   GuildId             { get; set; } // numeric(20,0)
		[Column("BirthdayChannelId"                                                                                   )] public ulong?  BirthdayChannelId   { get; set; } // numeric(20,0)
		[Column("BirthdayRoleId"                                                                                      )] public ulong?  BirthdayRoleId      { get; set; } // numeric(20,0)
		[Column("BirthdayMessage"                                                                                     )] public string?   BirthdayMessage     { get; set; } // text
		[Column("BirthdayPingRoleId"                                                                                  )] public ulong?  BirthdayPingRoleId  { get; set; } // numeric(20,0)
		[Column("BirthdayReminderDays"                                                                                )] public int       BirthdayReminderDays { get; set; } // integer
		[Column("DefaultTimezone"                                                                                     )] public string?   DefaultTimezone     { get; set; } // text
		[Column("EnabledFeatures"                                                                                     )] public int       EnabledFeatures     { get; set; } // integer
		[Column("LastAnnouncementDate"                                                                                )] public DateTime? LastAnnouncementDate { get; set; } // date
		[Column("DateAdded"                                                                                           )] public DateTime? DateAdded           { get; set; } // timestamp (6) without time zone
		[Column("DateModified"                                                                                        )] public DateTime? DateModified       { get; set; } // timestamp (6) without time zone
	}
}