// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("BotReviews")]
	public class BotReview
	{
		[Column("Id"       , IsPrimaryKey = true , IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int       Id        { get; set; } // integer
		[Column("UserId"                                                                                      )] public ulong   UserId    { get; set; } // numeric(20,0)
		[Column("AvatarUrl", CanBeNull    = false                                                             )] public string    AvatarUrl { get; set; } = null!; // text
		[Column("Stars"                                                                                       )] public int       Stars     { get; set; } // integer
		[Column("Review"   , CanBeNull    = false                                                             )] public string    Review    { get; set; } = null!; // text
		[Column("DateAdded"                                                                                   )] public DateTime? DateAdded { get; set; } // timestamp (6) without time zone
		[Column("Username" , CanBeNull    = false                                                             )] public string    Username  { get; set; } = null!; // text
	}
}
