// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("CommandStats")]
	public class CommandStat
	{
		[Column("Id"       , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int       Id        { get; set; } // integer
		[Column("NameOrId"                                                                                   )] public string?   NameOrId  { get; set; } // text
		[Column("Module"                                                                                     )] public string?   Module    { get; set; } // text
		[Column("IsSlash"                                                                                    )] public bool      IsSlash   { get; set; } // boolean
		[Column("Trigger"                                                                                    )] public bool      Trigger   { get; set; } // boolean
		[Column("GuildId"                                                                                    )] public ulong   GuildId   { get; set; } // numeric(20,0)
		[Column("ChannelId"                                                                                  )] public ulong   ChannelId { get; set; } // numeric(20,0)
		[Column("UserId"                                                                                     )] public ulong   UserId    { get; set; } // numeric(20,0)
		[Column("DateAdded"                                                                                  )] public DateTime? DateAdded { get; set; } // timestamp (6) without time zone
	}
}
