// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("CustomVoiceConfig")]
	public class CustomVoiceConfig
	{
		[Column("Id"                         , IsPrimaryKey = true , IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int       Id                          { get; set; } // integer
		[Column("GuildId"                                                                                                       )] public ulong   GuildId                     { get; set; } // numeric(20,0)
		[Column("HubVoiceChannelId"                                                                                             )] public ulong   HubVoiceChannelId           { get; set; } // numeric(20,0)
		[Column("ChannelCategoryId"                                                                                             )] public ulong?  ChannelCategoryId           { get; set; } // numeric(20,0)
		[Column("DefaultNameFormat"          , CanBeNull    = false                                                             )] public string    DefaultNameFormat           { get; set; } = null!; // text
		[Column("DefaultUserLimit"                                                                                              )] public int       DefaultUserLimit            { get; set; } // integer
		[Column("DefaultBitrate"                                                                                                )] public int       DefaultBitrate              { get; set; } // integer
		[Column("DeleteWhenEmpty"                                                                                               )] public bool      DeleteWhenEmpty             { get; set; } // boolean
		[Column("EmptyChannelTimeout"                                                                                           )] public int       EmptyChannelTimeout         { get; set; } // integer
		[Column("AllowMultipleChannels"                                                                                         )] public bool      AllowMultipleChannels       { get; set; } // boolean
		[Column("AllowNameCustomization"                                                                                        )] public bool      AllowNameCustomization      { get; set; } // boolean
		[Column("AllowUserLimitCustomization"                                                                                   )] public bool      AllowUserLimitCustomization { get; set; } // boolean
		[Column("AllowBitrateCustomization"                                                                                     )] public bool      AllowBitrateCustomization   { get; set; } // boolean
		[Column("AllowLocking"                                                                                                  )] public bool      AllowLocking                { get; set; } // boolean
		[Column("AllowUserManagement"                                                                                           )] public bool      AllowUserManagement         { get; set; } // boolean
		[Column("MaxUserLimit"                                                                                                  )] public int       MaxUserLimit                { get; set; } // integer
		[Column("MaxBitrate"                                                                                                    )] public int       MaxBitrate                  { get; set; } // integer
		[Column("PersistUserPreferences"                                                                                        )] public bool      PersistUserPreferences      { get; set; } // boolean
		[Column("AutoPermission"                                                                                                )] public bool      AutoPermission              { get; set; } // boolean
		[Column("CustomVoiceAdminRoleId"                                                                                        )] public ulong?  CustomVoiceAdminRoleId      { get; set; } // numeric(20,0)
		[Column("DateAdded"                                                                                                     )] public DateTime? DateAdded                   { get; set; } // timestamp (6) without time zone
	}
}
