// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("CustomVoiceChannel")]
	public class CustomVoiceChannel
	{
		[Column("Id"              , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int       Id               { get; set; } // integer
		[Column("GuildId"                                                                                           )] public ulong   GuildId          { get; set; } // numeric(20,0)
		[Column("ChannelId"                                                                                         )] public ulong   ChannelId        { get; set; } // numeric(20,0)
		[Column("OwnerId"                                                                                           )] public ulong   OwnerId          { get; set; } // numeric(20,0)
		[Column("CreatedAt"                                                                                         )] public DateTime  CreatedAt        { get; set; } // timestamp (6) without time zone
		[Column("LastActive"                                                                                        )] public DateTime  LastActive       { get; set; } // timestamp (6) without time zone
		[Column("IsLocked"                                                                                          )] public bool      IsLocked         { get; set; } // boolean
		[Column("KeepAlive"                                                                                         )] public bool      KeepAlive        { get; set; } // boolean
		[Column("AllowedUsersJson"                                                                                  )] public string?   AllowedUsersJson { get; set; } // text
		[Column("DeniedUsersJson"                                                                                   )] public string?   DeniedUsersJson  { get; set; } // text
		[Column("DateAdded"                                                                                         )] public DateTime? DateAdded        { get; set; } // timestamp (6) without time zone
	}
}
