// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("GuildUserXp")]
	public class GuildUserXp
	{
		[Column("GuildId"     , IsPrimaryKey = true, PrimaryKeyOrder = 0)] public ulong   GuildId      { get; set; } // numeric(20,0)
		[Column("UserId"      , IsPrimaryKey = true, PrimaryKeyOrder = 1)] public ulong   UserId       { get; set; } // numeric(20,0)
		[Column("TotalXp"                                               )] public long      TotalXp      { get; set; } // bigint
		[Column("BonusXp"                                               )] public long      BonusXp      { get; set; } // bigint
		[Column("LastActivity"                                          )] public DateTime  LastActivity { get; set; } // timestamp (6) without time zone
		[Column("NotifyType"                                            )] public int       NotifyType   { get; set; } // integer
		[Column("LastLevelUp"                                           )] public DateTime  LastLevelUp  { get; set; } // timestamp (6) without time zone
		[Column("Id"                                                    )] public int       Id           { get; set; } // integer
		[Column("DateAdded"                                             )] public DateTime? DateAdded    { get; set; } // timestamp (6) without time zone
	}
}
