// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("LoggingV2")]
	public class LoggingV2
	{
		[Column("Id"                   , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int       Id                    { get; set; } // integer
		[Column("GuildId"                                                                                                )] public ulong   GuildId               { get; set; } // numeric(20,0)
		[Column("LogOtherId"                                                                                             )] public ulong?  LogOtherId            { get; set; } // numeric(20,0)
		[Column("MessageUpdatedId"                                                                                       )] public ulong?  MessageUpdatedId      { get; set; } // numeric(20,0)
		[Column("MessageDeletedId"                                                                                       )] public ulong?  MessageDeletedId      { get; set; } // numeric(20,0)
		[Column("ThreadCreatedId"                                                                                        )] public ulong?  ThreadCreatedId       { get; set; } // numeric(20,0)
		[Column("ThreadDeletedId"                                                                                        )] public ulong?  ThreadDeletedId       { get; set; } // numeric(20,0)
		[Column("ThreadUpdatedId"                                                                                        )] public ulong?  ThreadUpdatedId       { get; set; } // numeric(20,0)
		[Column("UsernameUpdatedId"                                                                                      )] public ulong?  UsernameUpdatedId     { get; set; } // numeric(20,0)
		[Column("NicknameUpdatedId"                                                                                      )] public ulong?  NicknameUpdatedId     { get; set; } // numeric(20,0)
		[Column("AvatarUpdatedId"                                                                                        )] public ulong?  AvatarUpdatedId       { get; set; } // numeric(20,0)
		[Column("UserLeftId"                                                                                             )] public ulong?  UserLeftId            { get; set; } // numeric(20,0)
		[Column("UserBannedId"                                                                                           )] public ulong?  UserBannedId          { get; set; } // numeric(20,0)
		[Column("UserUnbannedId"                                                                                         )] public ulong?  UserUnbannedId        { get; set; } // numeric(20,0)
		[Column("UserUpdatedId"                                                                                          )] public ulong?  UserUpdatedId         { get; set; } // numeric(20,0)
		[Column("UserJoinedId"                                                                                           )] public ulong?  UserJoinedId          { get; set; } // numeric(20,0)
		[Column("UserRoleAddedId"                                                                                        )] public ulong?  UserRoleAddedId       { get; set; } // numeric(20,0)
		[Column("UserRoleRemovedId"                                                                                      )] public ulong?  UserRoleRemovedId     { get; set; } // numeric(20,0)
		[Column("UserMutedId"                                                                                            )] public ulong?  UserMutedId           { get; set; } // numeric(20,0)
		[Column("LogUserPresenceId"                                                                                      )] public ulong?  LogUserPresenceId     { get; set; } // numeric(20,0)
		[Column("LogVoicePresenceId"                                                                                     )] public ulong?  LogVoicePresenceId    { get; set; } // numeric(20,0)
		[Column("LogVoicePresenceTtsId"                                                                                  )] public ulong?  LogVoicePresenceTtsId { get; set; } // numeric(20,0)
		[Column("ServerUpdatedId"                                                                                        )] public ulong?  ServerUpdatedId       { get; set; } // numeric(20,0)
		[Column("RoleUpdatedId"                                                                                          )] public ulong?  RoleUpdatedId         { get; set; } // numeric(20,0)
		[Column("RoleDeletedId"                                                                                          )] public ulong?  RoleDeletedId         { get; set; } // numeric(20,0)
		[Column("EventCreatedId"                                                                                         )] public ulong?  EventCreatedId        { get; set; } // numeric(20,0)
		[Column("RoleCreatedId"                                                                                          )] public ulong?  RoleCreatedId         { get; set; } // numeric(20,0)
		[Column("ChannelCreatedId"                                                                                       )] public ulong?  ChannelCreatedId      { get; set; } // numeric(20,0)
		[Column("ChannelDestroyedId"                                                                                     )] public ulong?  ChannelDestroyedId    { get; set; } // numeric(20,0)
		[Column("ChannelUpdatedId"                                                                                       )] public ulong?  ChannelUpdatedId      { get; set; } // numeric(20,0)
		[Column("InviteCreatedId"                                                                                        )] public ulong?  InviteCreatedId       { get; set; } // numeric(20,0)
		[Column("InviteDeletedId"                                                                                        )] public ulong?  InviteDeletedId       { get; set; } // numeric(20,0)
		[Column("MessagesBulkDeletedId"                                                                                  )] public ulong?  MessagesBulkDeletedId { get; set; } // numeric(20,0)
		[Column("ReactionEventsId"                                                                                       )] public ulong?  ReactionEventsId      { get; set; } // numeric(20,0)
		[Column("DateAdded"                                                                                              )] public DateTime? DateAdded             { get; set; } // timestamp (6) without time zone
	}
}
