// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("MessageTimestamps")]
	public class MessageTimestamp
	{
		[Column("Id"            , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public long     Id             { get; set; } // bigint
		[Column("GuildId"                                                                                         )] public ulong  GuildId        { get; set; } // numeric(20,0)
		[Column("ChannelId"                                                                                       )] public ulong  ChannelId      { get; set; } // numeric(20,0)
		[Column("UserId"                                                                                          )] public ulong  UserId         { get; set; } // numeric(20,0)
		[Column("Timestamp"                                                                                       )] public DateTime Timestamp      { get; set; } // timestamp (6) without time zone
		[Column("MessageCountId"                                                                                  )] public long     MessageCountId { get; set; } // bigint

		#region Associations
		/// <summary>
		/// FK_MessageTimestamps_MessageCounts_MessageCountId
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(MessageCountId), OtherKey = nameof(DataModel.MessageCount.Id))]
		public MessageCount MessageCount { get; set; } = null!;
		#endregion
	}
}
