// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("NoteEdits")]
	public class NoteEdit
	{
		[Column("Id"          , IsPrimaryKey = true , IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int      Id           { get; set; } // integer
		[Column("OldContent"  , CanBeNull    = false                                                             )] public string   OldContent   { get; set; } = null!; // text
		[Column("NewContent"  , CanBeNull    = false                                                             )] public string   NewContent   { get; set; } = null!; // text
		[Column("EditorId"                                                                                       )] public ulong  EditorId     { get; set; } // numeric(20,0)
		[Column("EditedAt"                                                                                       )] public DateTime EditedAt     { get; set; } // timestamp (6) without time zone
		[Column("CaseNoteId"                                                                                     )] public int?     CaseNoteId   { get; set; } // integer
		[Column("TicketNoteId"                                                                                   )] public int?     TicketNoteId { get; set; } // integer

		#region Associations
		/// <summary>
		/// FK_NoteEdits_CaseNotes_CaseNoteId
		/// </summary>
		[Association(ThisKey = nameof(CaseNoteId), OtherKey = nameof(DataModel.CaseNote.Id))]
		public CaseNote? CaseNote { get; set; }

		/// <summary>
		/// FK_NoteEdits_TicketNotes_TicketNoteId
		/// </summary>
		[Association(ThisKey = nameof(TicketNoteId), OtherKey = nameof(DataModel.TicketNote.Id))]
		public TicketNote? TicketNote { get; set; }
		#endregion
	}
}
