// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("OwnerOnly")]
	public class OwnerOnly
	{
		[Column("Id"                  , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int       Id                   { get; set; } // integer
		[Column("Owners"                                                                                                )] public string?   Owners               { get; set; } // text
		[Column("GptTokensUsed"                                                                                         )] public int       GptTokensUsed        { get; set; } // integer
		[Column("CurrencyEmote"                                                                                         )] public string?   CurrencyEmote        { get; set; } // text
		[Column("RewardAmount"                                                                                          )] public int       RewardAmount         { get; set; } // integer
		[Column("RewardTimeoutSeconds"                                                                                  )] public int       RewardTimeoutSeconds { get; set; } // integer
		[Column("DateAdded"                                                                                             )] public DateTime? DateAdded            { get; set; } // timestamp (6) without time zone
	}
}
