// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("PanelSelectMenus")]
	public class PanelSelectMenu
	{
		[Column("Id"         , IsPrimaryKey = true , IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int    Id          { get; set; } // integer
		[Column("PanelId"                                                                                       )] public int    PanelId     { get; set; } // integer
		[Column("CustomId"   , CanBeNull    = false                                                             )] public string CustomId    { get; set; } = null!; // text
		[Column("Placeholder", CanBeNull    = false                                                             )] public string Placeholder { get; set; } = null!; // text

		#region Associations
		/// <summary>
		/// FK_PanelSelectMenus_TicketPanels_PanelId
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(PanelId), OtherKey = nameof(TicketPanel.Id))]
		public TicketPanel Panel { get; set; } = null!;

		/// <summary>
		/// FK_SelectMenuOptions_PanelSelectMenus_SelectMenuId backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(SelectMenuOption.SelectMenuId))]
		public IEnumerable<SelectMenuOption> SelectMenuOptions { get; set; } = null!;
		#endregion
	}
}
