// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("Permission")]
	public class Permission
	{
		[Column("Id"                 , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int       Id                  { get; set; } // integer
		[Column("NextId"                                                                                               )] public int       NextId              { get; set; } // integer
		[Column("PrimaryTarget"                                                                                        )] public int       PrimaryTarget       { get; set; } // integer
		[Column("PrimaryTargetId"                                                                                      )] public ulong   PrimaryTargetId     { get; set; } // numeric(20,0)
		[Column("SecondaryTarget"                                                                                      )] public int       SecondaryTarget     { get; set; } // integer
		[Column("SecondaryTargetName"                                                                                  )] public string?   SecondaryTargetName { get; set; } // text
		[Column("State"                                                                                                )] public bool      State               { get; set; } // boolean
		[Column("DateAdded"                                                                                            )] public DateTime? DateAdded           { get; set; } // timestamp (6) without time zone

		#region Associations
		/// <summary>
		/// FK_Permission_Permission_NextId
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(NextId), OtherKey = nameof(Id))]
		public Permission Next { get; set; } = null!;

		/// <summary>
		/// FK_Permission_Permission_NextId backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(NextId))]
		public IEnumerable<Permission> Permissions { get; set; } = null!;
		#endregion
	}

	[Table("Permissions")]
	public class Permission1
	{
		[Column("Id"                 , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int       Id                  { get; set; } // integer
		[Column("PrimaryTarget"                                                                                        )] public int       PrimaryTarget       { get; set; } // integer
		[Column("PrimaryTargetId"                                                                                      )] public ulong   PrimaryTargetId     { get; set; } // numeric(20,0)
		[Column("SecondaryTarget"                                                                                      )] public int       SecondaryTarget     { get; set; } // integer
		[Column("SecondaryTargetName"                                                                                  )] public string?   SecondaryTargetName { get; set; } // text
		[Column("IsCustomCommand"                                                                                      )] public bool      IsCustomCommand     { get; set; } // boolean
		[Column("State"                                                                                                )] public bool      State               { get; set; } // boolean
		[Column("Index"                                                                                                )] public int       Index               { get; set; } // integer
		[Column("DateAdded"                                                                                            )] public DateTime? DateAdded           { get; set; } // timestamp (6) without time zone
		[Column("GuildId"                                                                                              )] public ulong?  GuildId             { get; set; } // numeric(20,0)
	}
}
