// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("PlaylistSong")]
	public class PlaylistSong
	{
		[Column("Id"             , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int       Id              { get; set; } // integer
		[Column("MusicPlaylistId"                                                                                  )] public int       MusicPlaylistId { get; set; } // integer
		[Column("Provider"                                                                                         )] public string?   Provider        { get; set; } // text
		[Column("ProviderType"                                                                                     )] public int       ProviderType    { get; set; } // integer
		[Column("Title"                                                                                            )] public string?   Title           { get; set; } // text
		[Column("Uri"                                                                                              )] public string?   Uri             { get; set; } // text
		[Column("Query"                                                                                            )] public string?   Query           { get; set; } // text
		[Column("DateAdded"                                                                                        )] public DateTime? DateAdded       { get; set; } // timestamp (6) without time zone
	}
}
