// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
    /// <summary>
    /// Represents a voting option within a poll.
    /// </summary>
    [Table("PollOptions")]
    public class PollOption
    {
        /// <summary>
        /// Gets or sets the unique identifier for the poll option.
        /// </summary>
        [Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the ID of the poll this option belongs to.
        /// </summary>
        [Column("PollId")]
        public int PollId { get; set; }

        /// <summary>
        /// Gets or sets the display text for this option.
        /// </summary>
        [Column("Text")]
        public string Text { get; set; } = null!;

        /// <summary>
        /// Gets or sets the zero-based index position of this option in the poll.
        /// </summary>
        [Column("Index")]
        public int Index { get; set; }

        /// <summary>
        /// Gets or sets the hex color code for this option's visual display.
        /// </summary>
        [Column("Color")]
        public string? Color { get; set; }

        /// <summary>
        /// Gets or sets the Discord emote string for this option.
        /// </summary>
        [Column("Emote")]
        public string? Emote { get; set; }

        #region Associations
        /// <summary>
        /// Gets or sets the poll this option belongs to.
        /// </summary>
        [Association(ThisKey = nameof(PollId), OtherKey = nameof(Poll.Id))]
        public Poll Poll { get; set; } = null!;
        #endregion
    }
}