// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
    /// <summary>
    /// Represents a user's vote on a poll.
    /// </summary>
    [Table("PollVotes")]
    public class PollVote
    {
        /// <summary>
        /// Gets or sets the unique identifier for the vote.
        /// </summary>
        [Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the ID of the poll this vote belongs to.
        /// </summary>
        [Column("PollId")]
        public int PollId { get; set; }

        /// <summary>
        /// Gets or sets the Discord user ID of the voter.
        /// </summary>
        [Column("UserId")]
        public ulong UserId { get; set; }

        /// <summary>
        /// Gets or sets the selected option indices as a JSON array.
        /// </summary>
        [Column("OptionIndices")]
        public string OptionIndices { get; set; } = null!;

        /// <summary>
        /// Gets or sets when the vote was cast.
        /// </summary>
        [Column("VotedAt")]
        public DateTime VotedAt { get; set; }

        /// <summary>
        /// Gets or sets whether this vote was cast anonymously.
        /// </summary>
        [Column("IsAnonymous")]
        public bool IsAnonymous { get; set; }

        #region Associations
        /// <summary>
        /// Gets or sets the poll this vote belongs to.
        /// </summary>
        [Association(ThisKey = nameof(PollId), OtherKey = nameof(Poll.Id))]
        public Poll Poll { get; set; } = null!;
        #endregion
    }
}