// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
    /// <summary>
    /// Represents a reusable poll template for quick poll creation.
    /// </summary>
    [Table("PollTemplates")]
    public class PollTemplate
    {
        /// <summary>
        /// Gets or sets the unique identifier for the template.
        /// </summary>
        [Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the Discord guild ID where the template is available.
        /// </summary>
        [Column("GuildId")]
        public ulong GuildId { get; set; }

        /// <summary>
        /// Gets or sets the template name for identification.
        /// </summary>
        [Column("Name")]
        public string Name { get; set; } = null!;

        /// <summary>
        /// Gets or sets the template question text.
        /// </summary>
        [Column("Question")]
        public string Question { get; set; } = null!;

        /// <summary>
        /// Gets or sets the template options as JSON array.
        /// </summary>
        [Column("Options")]
        public string Options { get; set; } = null!;

        /// <summary>
        /// Gets or sets the template settings as JSON.
        /// </summary>
        [Column("Settings")]
        public string? Settings { get; set; }

        /// <summary>
        /// Gets or sets the Discord user ID of the template creator.
        /// </summary>
        [Column("CreatorId")]
        public ulong CreatorId { get; set; }

        /// <summary>
        /// Gets or sets when the template was created.
        /// </summary>
        [Column("CreatedAt")]
        public DateTime CreatedAt { get; set; }
    }
}