// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("Quotes")]
	public class Quote
	{
		[Column("Id"        , IsPrimaryKey = true , IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int       Id         { get; set; } // integer
		[Column("GuildId"                                                                                      )] public ulong   GuildId    { get; set; } // numeric(20,0)
		[Column("Keyword"   , CanBeNull    = false                                                             )] public string    Keyword    { get; set; } = null!; // text
		[Column("AuthorName", CanBeNull    = false                                                             )] public string    AuthorName { get; set; } = null!; // text
		[Column("AuthorId"                                                                                     )] public ulong   AuthorId   { get; set; } // numeric(20,0)
		[Column("Text"      , CanBeNull    = false                                                             )] public string    Text       { get; set; } = null!; // text
		[Column("UseCount"                                                                                     )] public ulong   UseCount   { get; set; } // numeric(20,0)
		[Column("DateAdded"                                                                                    )] public DateTime? DateAdded  { get; set; } // timestamp (6) without time zone
	}
}
