// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("ReactionRoleMessages")]
	public class ReactionRoleMessage
	{
		[Column("Id"       , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int       Id        { get; set; } // integer
		[Column("ChannelId"                                                                                  )] public ulong   ChannelId { get; set; } // numeric(20,0)
		[Column("MessageId"                                                                                  )] public ulong   MessageId { get; set; } // numeric(20,0)
		[Column("Exclusive"                                                                                  )] public bool      Exclusive { get; set; } // boolean
		[Column("Index"                                                                                      )] public int       Index     { get; set; } // integer
		[Column("DateAdded"                                                                                  )] public DateTime? DateAdded { get; set; } // timestamp (6) without time zone
		[Column("GuildId"                                                                                    )] public ulong?  GuildId   { get; set; } // numeric(20,0)

		#region Associations
		/// <summary>
		/// FK_ReactionRole_ReactionRoleMessage_ReactionRoleMessageId backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(ReactionRole.ReactionRoleMessageId))]
		public IEnumerable<ReactionRole> ReactionRoles { get; set; } = null!;
		#endregion
	}
}
