// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("Starboards")]
	public class Starboard
	{
		[Column("Id"                    , IsPrimaryKey = true , IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int       Id                     { get; set; } // integer
		[Column("GuildId"                                                                                                  )] public ulong   GuildId                { get; set; } // numeric(20,0)
		[Column("StarboardChannelId"                                                                                       )] public ulong   StarboardChannelId     { get; set; } // numeric(20,0)
		[Column("Emote"                 , CanBeNull    = false                                                             )] public string    Emote                  { get; set; } = null!; // text
		[Column("Threshold"                                                                                                )] public int       Threshold              { get; set; } // integer
		[Column("CheckedChannels"       , CanBeNull    = false                                                             )] public string    CheckedChannels        { get; set; } = null!; // text
		[Column("UseBlacklist"                                                                                             )] public bool      UseBlacklist           { get; set; } // boolean
		[Column("AllowBots"                                                                                                )] public bool      AllowBots              { get; set; } // boolean
		[Column("RemoveOnDelete"                                                                                           )] public bool      RemoveOnDelete         { get; set; } // boolean
		[Column("RemoveOnReactionsClear"                                                                                   )] public bool      RemoveOnReactionsClear { get; set; } // boolean
		[Column("RemoveOnBelowThreshold"                                                                                   )] public bool      RemoveOnBelowThreshold { get; set; } // boolean
		[Column("RepostThreshold"                                                                                          )] public int       RepostThreshold        { get; set; } // integer
		[Column("DateAdded"                                                                                                )] public DateTime? DateAdded              { get; set; } // timestamp (6) without time zone
	}
}
