// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("StatusRoles")]
	public class StatusRole
	{
		[Column("Id"             , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int       Id              { get; set; } // integer
		[Column("GuildId"                                                                                          )] public ulong   GuildId         { get; set; } // numeric(20,0)
		[Column("Status"                                                                                           )] public string?   Status          { get; set; } // text
		[Column("ToAdd"                                                                                            )] public string?   ToAdd           { get; set; } // text
		[Column("ToRemove"                                                                                         )] public string?   ToRemove        { get; set; } // text
		[Column("StatusEmbed"                                                                                      )] public string?   StatusEmbed     { get; set; } // text
		[Column("ReaddRemoved"                                                                                     )] public bool      ReaddRemoved    { get; set; } // boolean
		[Column("RemoveAdded"                                                                                      )] public bool      RemoveAdded     { get; set; } // boolean
		[Column("StatusChannelId"                                                                                  )] public ulong   StatusChannelId { get; set; } // numeric(20,0)
		[Column("DateAdded"                                                                                        )] public DateTime? DateAdded       { get; set; } // timestamp (6) without time zone
	}
}
