// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("StreamRoleSettings")]
	public class StreamRoleSetting
	{
		[Column("Id"        , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int       Id         { get; set; } // integer
		[Column("Enabled"                                                                                     )] public bool      Enabled    { get; set; } // boolean
		[Column("AddRoleId"                                                                                   )] public ulong   AddRoleId  { get; set; } // numeric(20,0)
		[Column("FromRoleId"                                                                                  )] public ulong   FromRoleId { get; set; } // numeric(20,0)
		[Column("Keyword"                                                                                     )] public string?   Keyword    { get; set; } // text
		[Column("DateAdded"                                                                                   )] public DateTime? DateAdded  { get; set; } // timestamp (6) without time zone
		[Column("GuildId"                                                                                     )] public ulong?  GuildId    { get; set; } // numeric(20,0)

		#region Associations
		/// <summary>
		/// FK_StreamRoleBlacklistedUser_StreamRoleSettings_StreamRoleSett~ backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(StreamRoleBlacklistedUser.StreamRoleSettingsId))]
		public IEnumerable<StreamRoleBlacklistedUser> StreamRoleBlacklistedUsers { get; set; } = null!;

		/// <summary>
		/// FK_StreamRoleWhitelistedUser_StreamRoleSettings_StreamRoleSett~ backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(StreamRoleWhitelistedUser.StreamRoleSettingsId))]
		public IEnumerable<StreamRoleWhitelistedUser> StreamRoleWhitelistedUsers { get; set; } = null!;
		#endregion
	}
}
