// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("Suggestions")]
	public class Suggestion
	{
		[Column("Id"                  , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int       Id                   { get; set; } // integer
		[Column("GuildId"                                                                                               )] public ulong   GuildId              { get; set; } // numeric(20,0)
		[Column("SuggestionId"                                                                                          )] public ulong   SuggestionId         { get; set; } // numeric(20,0)
		[Column("Suggestion"                                                                                            )] public string?   Suggestion1          { get; set; } // text
		[Column("MessageId"                                                                                             )] public ulong   MessageId            { get; set; } // numeric(20,0)
		[Column("UserId"                                                                                                )] public ulong   UserId               { get; set; } // numeric(20,0)
		[Column("EmoteCount1"                                                                                           )] public int       EmoteCount1          { get; set; } // integer
		[Column("EmoteCount2"                                                                                           )] public int       EmoteCount2          { get; set; } // integer
		[Column("EmoteCount3"                                                                                           )] public int       EmoteCount3          { get; set; } // integer
		[Column("EmoteCount4"                                                                                           )] public int       EmoteCount4          { get; set; } // integer
		[Column("EmoteCount5"                                                                                           )] public int       EmoteCount5          { get; set; } // integer
		[Column("StateChangeUser"                                                                                       )] public ulong   StateChangeUser      { get; set; } // numeric(20,0)
		[Column("StateChangeCount"                                                                                      )] public ulong   StateChangeCount     { get; set; } // numeric(20,0)
		[Column("StateChangeMessageId"                                                                                  )] public ulong   StateChangeMessageId { get; set; } // numeric(20,0)
		[Column("CurrentState"                                                                                          )] public int       CurrentState         { get; set; } // integer
		[Column("DateAdded"                                                                                             )] public DateTime? DateAdded            { get; set; } // timestamp (6) without time zone
	}
}
