// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("TemplateGuild")]
	public class TemplateGuild
	{
		[Column("Id"                , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int       Id                 { get; set; } // integer
		[Column("GuildLevelColor"                                                                                     )] public string?   GuildLevelColor    { get; set; } // text
		[Column("GuildLevelFontSize"                                                                                  )] public int       GuildLevelFontSize { get; set; } // integer
		[Column("GuildLevelX"                                                                                         )] public int       GuildLevelX        { get; set; } // integer
		[Column("GuildLevelY"                                                                                         )] public int       GuildLevelY        { get; set; } // integer
		[Column("ShowGuildLevel"                                                                                      )] public bool      ShowGuildLevel     { get; set; } // boolean
		[Column("GuildRankColor"                                                                                      )] public string?   GuildRankColor     { get; set; } // text
		[Column("GuildRankFontSize"                                                                                   )] public int       GuildRankFontSize  { get; set; } // integer
		[Column("GuildRankX"                                                                                          )] public int       GuildRankX         { get; set; } // integer
		[Column("GuildRankY"                                                                                          )] public int       GuildRankY         { get; set; } // integer
		[Column("ShowGuildRank"                                                                                       )] public bool      ShowGuildRank      { get; set; } // boolean
		[Column("DateAdded"                                                                                           )] public DateTime? DateAdded          { get; set; } // timestamp (6) without time zone

		#region Associations
		/// <summary>
		/// FK_Template_TemplateGuild_TemplateGuildId backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(Template.TemplateGuildId))]
        [JsonIgnore]
		public IEnumerable<Template> Templates { get; set; } = null!;
		#endregion
	}
}
