// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("TemplateUser")]
	public class TemplateUser
	{
		[Column("Id"       , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int       Id        { get; set; } // integer
		[Column("TextColor"                                                                                  )] public string?   TextColor { get; set; } // text
		[Column("FontSize"                                                                                   )] public int       FontSize  { get; set; } // integer
		[Column("TextX"                                                                                      )] public int       TextX     { get; set; } // integer
		[Column("TextY"                                                                                      )] public int       TextY     { get; set; } // integer
		[Column("ShowText"                                                                                   )] public bool      ShowText  { get; set; } // boolean
		[Column("IconX"                                                                                      )] public int       IconX     { get; set; } // integer
		[Column("IconY"                                                                                      )] public int       IconY     { get; set; } // integer
		[Column("IconSizeX"                                                                                  )] public int       IconSizeX { get; set; } // integer
		[Column("IconSizeY"                                                                                  )] public int       IconSizeY { get; set; } // integer
		[Column("ShowIcon"                                                                                   )] public bool      ShowIcon  { get; set; } // boolean
		[Column("DateAdded"                                                                                  )] public DateTime? DateAdded { get; set; } // timestamp (6) without time zone

		#region Associations
		/// <summary>
		/// FK_Template_TemplateUser_TemplateUserId backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(Template.TemplateUserId))]
        [JsonIgnore]
		public IEnumerable<Template> Templates { get; set; } = null!;
		#endregion
	}
}
