// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("TemplateBar")]
	public class TemplateBar
	{
		[Column("Id"             , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int       Id              { get; set; } // integer
		[Column("BarColor"                                                                                         )] public string?   BarColor        { get; set; } // text
		[Column("BarPointAx"                                                                                       )] public int       BarPointAx      { get; set; } // integer
		[Column("BarPointAy"                                                                                       )] public int       BarPointAy      { get; set; } // integer
		[Column("BarPointBx"                                                                                       )] public int       BarPointBx      { get; set; } // integer
		[Column("BarPointBy"                                                                                       )] public int       BarPointBy      { get; set; } // integer
		[Column("BarLength"                                                                                        )] public int       BarLength       { get; set; } // integer
		[Column("BarTransparency"                                                                                  )] public short     BarTransparency { get; set; } // smallint
		[Column("BarDirection"                                                                                     )] public int       BarDirection    { get; set; } // integer
		[Column("ShowBar"                                                                                          )] public bool      ShowBar         { get; set; } // boolean
		[Column("DateAdded"                                                                                        )] public DateTime? DateAdded       { get; set; } // timestamp (6) without time zone

		#region Associations
		/// <summary>
		/// FK_Template_TemplateBar_TemplateBarId backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(Template.TemplateBarId))]
        [JsonIgnore]
		public IEnumerable<Template> Templates { get; set; } = null!;
		#endregion
	}
}
