// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("TemplateClub")]
	public class TemplateClub
	{
		[Column("Id"              , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int       Id               { get; set; } // integer
		[Column("ClubIconX"                                                                                         )] public int       ClubIconX        { get; set; } // integer
		[Column("ClubIconY"                                                                                         )] public int       ClubIconY        { get; set; } // integer
		[Column("ClubIconSizeX"                                                                                     )] public int       ClubIconSizeX    { get; set; } // integer
		[Column("ClubIconSizeY"                                                                                     )] public int       ClubIconSizeY    { get; set; } // integer
		[Column("ShowClubIcon"                                                                                      )] public bool      ShowClubIcon     { get; set; } // boolean
		[Column("ClubNameColor"                                                                                     )] public string?   ClubNameColor    { get; set; } // text
		[Column("ClubNameFontSize"                                                                                  )] public int       ClubNameFontSize { get; set; } // integer
		[Column("ClubNameX"                                                                                         )] public int       ClubNameX        { get; set; } // integer
		[Column("ClubNameY"                                                                                         )] public int       ClubNameY        { get; set; } // integer
		[Column("ShowClubName"                                                                                      )] public bool      ShowClubName     { get; set; } // boolean
		[Column("DateAdded"                                                                                         )] public DateTime? DateAdded        { get; set; } // timestamp (6) without time zone

		#region Associations
		/// <summary>
		/// FK_Template_TemplateClub_TemplateClubId backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(Template.TemplateClubId))]
        [JsonIgnore]
		public IEnumerable<Template> Templates { get; set; } = null!;
		#endregion
	}
}
