// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("TicketNotes")]
	public class TicketNote
	{
		[Column("Id"       , IsPrimaryKey = true , IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int      Id        { get; set; } // integer
		[Column("TicketId"                                                                                    )] public int      TicketId  { get; set; } // integer
		[Column("AuthorId"                                                                                    )] public ulong  AuthorId  { get; set; } // numeric(20,0)
		[Column("Content"  , CanBeNull    = false                                                             )] public string   Content   { get; set; } = null!; // text
		[Column("CreatedAt"                                                                                   )] public DateTime CreatedAt { get; set; } // timestamp (6) without time zone

		#region Associations
		/// <summary>
		/// FK_NoteEdits_TicketNotes_TicketNoteId backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(NoteEdit.TicketNoteId))]
		public IEnumerable<NoteEdit> NoteEdits { get; set; } = null!;

		/// <summary>
		/// FK_TicketNotes_Tickets_TicketId
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(TicketId), OtherKey = nameof(DataModel.Ticket.Id))]
		public Ticket Ticket { get; set; } = null!;
		#endregion
	}
}
