// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
    [Table("TodoLists")]
    public class TodoList
    {
        [Column("Id"          , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int       Id           { get; set; } // integer
        [Column("Name"                                                                                        )] public string    Name         { get; set; } = null!; // text
        [Column("Description"                                                                                 )] public string?   Description  { get; set; } // text
        [Column("GuildId"                                                                                     )] public ulong     GuildId      { get; set; } // numeric(20,0)
        [Column("OwnerId"                                                                                     )] public ulong     OwnerId      { get; set; } // numeric(20,0)
        [Column("IsServerList"                                                                                )] public bool      IsServerList { get; set; } // boolean
        [Column("IsPublic"                                                                                    )] public bool      IsPublic     { get; set; } // boolean
        [Column("Color"                                                                                       )] public string?   Color        { get; set; } // text
        [Column("CreatedAt"                                                                                   )] public DateTime  CreatedAt    { get; set; } // timestamp (6) without time zone
        [Column("UpdatedAt"                                                                                   )] public DateTime  UpdatedAt    { get; set; } // timestamp (6) without time zone
    }
}