// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
    [Table("TodoItems")]
    public class TodoItem
    {
        [Column("Id"           , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int       Id           { get; set; } // integer
        [Column("TodoListId"                                                                                   )] public int       TodoListId   { get; set; } // integer
        [Column("Title"                                                                                        )] public string    Title        { get; set; } = null!; // text
        [Column("Description"                                                                                  )] public string?   Description  { get; set; } // text
        [Column("IsCompleted"                                                                                  )] public bool      IsCompleted  { get; set; } // boolean
        [Column("Priority"                                                                                     )] public int       Priority     { get; set; } // integer
        [Column("DueDate"                                                                                      )] public DateTime? DueDate      { get; set; } // timestamp (6) without time zone
        [Column("CreatedAt"                                                                                    )] public DateTime  CreatedAt    { get; set; } // timestamp (6) without time zone
        [Column("CompletedAt"                                                                                  )] public DateTime? CompletedAt  { get; set; } // timestamp (6) without time zone
        [Column("CreatedBy"                                                                                    )] public ulong     CreatedBy    { get; set; } // numeric(20,0)
        [Column("CompletedBy"                                                                                  )] public ulong?    CompletedBy  { get; set; } // numeric(20,0)
        [Column("Tags"                                                                                         )] public string[]? Tags         { get; set; } // text[]
        [Column("ReminderTime"                                                                                 )] public DateTime? ReminderTime { get; set; } // timestamp (6) without time zone
        [Column("Position"                                                                                     )] public int       Position     { get; set; } // integer
    }
}