// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
    [Table("TodoListPermissions")]
    public class TodoListPermission
    {
        [Column("Id"           , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int      Id            { get; set; } // integer
        [Column("TodoListId"                                                                                   )] public int      TodoListId    { get; set; } // integer
        [Column("UserId"                                                                                       )] public ulong    UserId        { get; set; } // numeric(20,0)
        [Column("CanView"                                                                                      )] public bool     CanView       { get; set; } // boolean
        [Column("CanAdd"                                                                                       )] public bool     CanAdd        { get; set; } // boolean
        [Column("CanEdit"                                                                                      )] public bool     CanEdit       { get; set; } // boolean
        [Column("CanComplete"                                                                                  )] public bool     CanComplete   { get; set; } // boolean
        [Column("CanDelete"                                                                                    )] public bool     CanDelete     { get; set; } // boolean
        [Column("CanManageList"                                                                                )] public bool     CanManageList { get; set; } // boolean
        [Column("GrantedBy"                                                                                    )] public ulong    GrantedBy     { get; set; } // numeric(20,0)
        [Column("GrantedAt"                                                                                    )] public DateTime GrantedAt     { get; set; } // timestamp (6) without time zone
    }
}