// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("UserVoicePreference")]
	public class UserVoicePreference
	{
		[Column("Id"           , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int       Id            { get; set; } // integer
		[Column("GuildId"                                                                                        )] public ulong   GuildId       { get; set; } // numeric(20,0)
		[Column("UserId"                                                                                         )] public ulong   UserId        { get; set; } // numeric(20,0)
		[Column("NameFormat"                                                                                     )] public string?   NameFormat    { get; set; } // text
		[Column("UserLimit"                                                                                      )] public int?      UserLimit     { get; set; } // integer
		[Column("Bitrate"                                                                                        )] public int?      Bitrate       { get; set; } // integer
		[Column("PreferLocked"                                                                                   )] public bool?     PreferLocked  { get; set; } // boolean
		[Column("KeepAlive"                                                                                      )] public bool?     KeepAlive     { get; set; } // boolean
		[Column("WhitelistJson"                                                                                  )] public string?   WhitelistJson { get; set; } // text
		[Column("BlacklistJson"                                                                                  )] public string?   BlacklistJson { get; set; } // text
		[Column("DateAdded"                                                                                      )] public DateTime? DateAdded     { get; set; } // timestamp (6) without time zone
	}
}
