// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("XpChannelMultipliers")]
	public class XpChannelMultiplier
	{
		[Column("GuildId"   , IsPrimaryKey = true, PrimaryKeyOrder = 0)] public ulong   GuildId    { get; set; } // numeric(20,0)
		[Column("ChannelId" , IsPrimaryKey = true, PrimaryKeyOrder = 1)] public ulong   ChannelId  { get; set; } // numeric(20,0)
		[Column("Multiplier"                                          )] public double    Multiplier { get; set; } // double precision
		[Column("Id"                                                  )] public int       Id         { get; set; } // integer
		[Column("DateAdded"                                           )] public DateTime? DateAdded  { get; set; } // timestamp (6) without time zone
	}
}
