// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("XpCompetitions")]
	public class XpCompetition
	{
		[Column("Id"                   , IsPrimaryKey = true , IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int       Id                    { get; set; } // integer
		[Column("GuildId"                                                                                                 )] public ulong   GuildId               { get; set; } // numeric(20,0)
		[Column("Name"                 , CanBeNull    = false                                                             )] public string    Name                  { get; set; } = null!; // text
		[Column("Type"                                                                                                    )] public int       Type                  { get; set; } // integer
		[Column("StartTime"                                                                                               )] public DateTime  StartTime             { get; set; } // timestamp (6) without time zone
		[Column("EndTime"                                                                                                 )] public DateTime  EndTime               { get; set; } // timestamp (6) without time zone
		[Column("TargetLevel"                                                                                             )] public int       TargetLevel           { get; set; } // integer
		[Column("AnnouncementChannelId"                                                                                   )] public ulong?  AnnouncementChannelId { get; set; } // numeric(20,0)
		[Column("DateAdded"                                                                                               )] public DateTime? DateAdded             { get; set; } // timestamp (6) without time zone
	}
}
