// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("XpCompetitionEntries")]
	public class XpCompetitionEntry
	{
		[Column("CompetitionId"   , IsPrimaryKey = true, PrimaryKeyOrder = 0)] public int       CompetitionId    { get; set; } // integer
		[Column("UserId"          , IsPrimaryKey = true, PrimaryKeyOrder = 1)] public ulong   UserId           { get; set; } // numeric(20,0)
		[Column("StartingXp"                                                )] public long      StartingXp       { get; set; } // bigint
		[Column("CurrentXp"                                                 )] public long      CurrentXp        { get; set; } // bigint
		[Column("AchievedTargetAt"                                          )] public DateTime? AchievedTargetAt { get; set; } // timestamp (6) without time zone
		[Column("FinalPlacement"                                            )] public int       FinalPlacement   { get; set; } // integer
		[Column("Id"                                                        )] public int       Id               { get; set; } // integer
		[Column("DateAdded"                                                 )] public DateTime? DateAdded        { get; set; } // timestamp (6) without time zone
	}
}
