// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("XpRoleTracking")]
	public class XpRoleTracking
	{
		[Column("GuildId"      , IsPrimaryKey = true , PrimaryKeyOrder = 0)] public ulong   GuildId       { get; set; } // numeric(20,0)
		[Column("RoleId"       , IsPrimaryKey = true , PrimaryKeyOrder = 1)] public ulong   RoleId        { get; set; } // numeric(20,0)
		[Column("StartTracking", IsPrimaryKey = true , PrimaryKeyOrder = 2)] public DateTime  StartTracking { get; set; } // timestamp (6) without time zone
		[Column("TotalXpGained"                                           )] public long      TotalXpGained { get; set; } // bigint
		[Column("EndTracking"                                             )] public DateTime? EndTracking   { get; set; } // timestamp (6) without time zone
		[Column("TrackingTitle", CanBeNull    = false                     )] public string    TrackingTitle { get; set; } = null!; // text
		[Column("Id"                                                      )] public int       Id            { get; set; } // integer
		[Column("DateAdded"                                               )] public DateTime? DateAdded     { get; set; } // timestamp (6) without time zone
	}
}
