DO
$$
BEGIN
    IF
NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'PanelButtons' AND column_name = 'Id'
        AND is_identity = 'YES'
    ) THEN
ALTER TABLE "PanelButtons" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY;
END IF;
END $$;

-- Update existing tables to use bigint[] instead of numeric(20,0)[]
DO
$$
BEGIN
    IF
EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'PanelButtons' AND column_name = 'SupportRoles' AND data_type != 'ARRAY') THEN
ALTER TABLE "PanelButtons" ALTER COLUMN "SupportRoles" TYPE bigint[];
END IF;
    IF
EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'PanelButtons' AND column_name = 'ViewerRoles' AND data_type != 'ARRAY') THEN
ALTER TABLE "PanelButtons" ALTER COLUMN "ViewerRoles" TYPE bigint[];
END IF;
END $$;

DO
$$
BEGIN
    IF
EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'SelectMenuOptions' AND column_name = 'SupportRoles' AND data_type != 'ARRAY') THEN
ALTER TABLE "SelectMenuOptions" ALTER COLUMN "SupportRoles" TYPE bigint[];
END IF;
    IF
EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'SelectMenuOptions' AND column_name = 'ViewerRoles' AND data_type != 'ARRAY') THEN
ALTER TABLE "SelectMenuOptions" ALTER COLUMN "ViewerRoles" TYPE bigint[];
END IF;
END $$;

-- Also update other Discord ID columns to bigint for consistency
DO
$$
BEGIN
    IF
EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'TicketPanels' AND column_name = 'GuildId' AND data_type = 'numeric') THEN
ALTER TABLE "TicketPanels" ALTER COLUMN "GuildId" TYPE bigint;
END IF;
    IF
EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'TicketPanels' AND column_name = 'ChannelId' AND data_type = 'numeric') THEN
ALTER TABLE "TicketPanels" ALTER COLUMN "ChannelId" TYPE bigint;
END IF;
    IF
EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'TicketPanels' AND column_name = 'MessageId' AND data_type = 'numeric') THEN
ALTER TABLE "TicketPanels" ALTER COLUMN "MessageId" TYPE bigint;
END IF;
END $$;

DO
$$
BEGIN
    IF
EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'PanelButtons' AND column_name = 'CategoryId' AND data_type = 'numeric') THEN
ALTER TABLE "PanelButtons" ALTER COLUMN "CategoryId" TYPE bigint;
END IF;
    IF
EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'PanelButtons' AND column_name = 'ArchiveCategoryId' AND data_type = 'numeric') THEN
ALTER TABLE "PanelButtons" ALTER COLUMN "ArchiveCategoryId" TYPE bigint;
END IF;
END $$;

DO
$$
BEGIN
    IF
EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'SelectMenuOptions' AND column_name = 'CategoryId' AND data_type = 'numeric') THEN
ALTER TABLE "SelectMenuOptions" ALTER COLUMN "CategoryId" TYPE bigint;
END IF;
    IF
EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'SelectMenuOptions' AND column_name = 'ArchiveCategoryId' AND data_type = 'numeric') THEN
ALTER TABLE "SelectMenuOptions" ALTER COLUMN "ArchiveCategoryId" TYPE bigint;
END IF;
END $$;

DO
$$
BEGIN
    IF
EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'Tickets' AND column_name = 'GuildId' AND data_type = 'numeric') THEN
ALTER TABLE "Tickets" ALTER COLUMN "GuildId" TYPE bigint;
END IF;
    IF
EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'Tickets' AND column_name = 'ChannelId' AND data_type = 'numeric') THEN
ALTER TABLE "Tickets" ALTER COLUMN "ChannelId" TYPE bigint;
END IF;
    IF
EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'Tickets' AND column_name = 'CreatorId' AND data_type = 'numeric') THEN
ALTER TABLE "Tickets" ALTER COLUMN "CreatorId" TYPE bigint;
END IF;
    IF
EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'Tickets' AND column_name = 'ClaimedBy' AND data_type = 'numeric') THEN
ALTER TABLE "Tickets" ALTER COLUMN "ClaimedBy" TYPE bigint;
END IF;
END $$;

DO
$$
BEGIN
    IF
EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'TicketCases' AND column_name = 'GuildId' AND data_type = 'numeric') THEN
ALTER TABLE "TicketCases" ALTER COLUMN "GuildId" TYPE bigint;
END IF;
    IF
EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'TicketCases' AND column_name = 'CreatedBy' AND data_type = 'numeric') THEN
ALTER TABLE "TicketCases" ALTER COLUMN "CreatedBy" TYPE bigint;
END IF;
END $$;

DO
$$
BEGIN
    IF
EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'CaseNotes' AND column_name = 'AuthorId' AND data_type = 'numeric') THEN
ALTER TABLE "CaseNotes" ALTER COLUMN "AuthorId" TYPE bigint;
END IF;
END $$;

DO
$$
BEGIN
    IF
EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'NoteEdits' AND column_name = 'EditorId' AND data_type = 'numeric') THEN
ALTER TABLE "NoteEdits" ALTER COLUMN "EditorId" TYPE bigint;
END IF;
END $$;

DO
$$
BEGIN
    IF
EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'TicketNotes' AND column_name = 'AuthorId' AND data_type = 'numeric') THEN
ALTER TABLE "TicketNotes" ALTER COLUMN "AuthorId" TYPE bigint;
END IF;
END $$;

ALTER TABLE "PanelButtons"
    ADD COLUMN IF NOT EXISTS "DeleteOnClose" BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS "LockOnClose" BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS "RenameOnClose" BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS "RemoveCreatorOnClose" BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS "DeleteDelay" INTERVAL NOT NULL DEFAULT INTERVAL '5 minutes',
    ADD COLUMN IF NOT EXISTS "LockOnArchive" BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS "RenameOnArchive" BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS "RemoveCreatorOnArchive" BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS "AutoArchiveOnClose" BOOLEAN NOT NULL DEFAULT FALSE;

-- Add enhanced close/archive behavior columns to SelectMenuOptions
ALTER TABLE "SelectMenuOptions"
    ADD COLUMN IF NOT EXISTS "DeleteOnClose" BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS "LockOnClose" BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS "RenameOnClose" BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS "RemoveCreatorOnClose" BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS "DeleteDelay" INTERVAL NOT NULL DEFAULT INTERVAL '5 minutes',
    ADD COLUMN IF NOT EXISTS "LockOnArchive" BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS "RenameOnArchive" BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS "RemoveCreatorOnArchive" BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS "AutoArchiveOnClose" BOOLEAN NOT NULL DEFAULT FALSE;

-- Add guild-wide default settings to GuildTicketSettings
ALTER TABLE "GuildTicketSettings"
    ADD COLUMN IF NOT EXISTS "DeleteTicketsOnClose" BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS "LockTicketsOnClose" BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS "RenameTicketsOnClose" BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS "RemoveCreatorOnClose" BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS "DeleteDelay" INTERVAL NOT NULL DEFAULT INTERVAL '5 minutes',
    ADD COLUMN IF NOT EXISTS "LockTicketsOnArchive" BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS "RenameTicketsOnArchive" BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS "RemoveCreatorOnArchive" BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS "AutoArchiveOnClose" BOOLEAN NOT NULL DEFAULT FALSE;

-- Add deletion tracking to Tickets table
ALTER TABLE "Tickets"
    ADD COLUMN IF NOT EXISTS "IsDeleted" BOOLEAN NOT NULL DEFAULT FALSE;

-- Create index for finding non-deleted tickets (performance optimization)
CREATE INDEX IF NOT EXISTS "IX_Tickets_IsDeleted_GuildId"
    ON "Tickets" ("IsDeleted", "GuildId")
    WHERE "IsDeleted" = FALSE;

-- Create index for auto-close queries (performance optimization)
CREATE INDEX IF NOT EXISTS "IX_Tickets_AutoClose_Lookup"
    ON "Tickets" ("IsArchived", "ClosedAt", "LastActivityAt")
    WHERE "IsArchived" = FALSE AND "ClosedAt" IS NULL;
